import type { Track } from "@/types";

export const SEED_TRACKS: Omit<Track, "id" | "createdAt">[] = [
  {
    title: "霓虹梦境",
    artist: "AI Radio",
    mode: "original",
    prompt: "synthwave, dreamy, neon, electronic",
    lyricsTheme: "未来城市的夜晚",
    language: "zh",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    streamUrl: null,
    coverUrl: null,
    durationMs: 372000,
    status: "ready",
    murekaTaskId: null,
    tags: ["synthwave", "electronic", "dreamy"],
  },
  {
    title: "午后咖啡",
    artist: "AI Radio",
    mode: "original",
    prompt: "acoustic, warm, indie folk, soft vocal",
    lyricsTheme: "咖啡馆的午后",
    language: "zh",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    streamUrl: null,
    coverUrl: null,
    durationMs: 425000,
    status: "ready",
    murekaTaskId: null,
    tags: ["acoustic", "folk", "warm"],
  },
  {
    title: "午夜节奏",
    artist: "AI Radio",
    mode: "original",
    prompt: "r&b, slow, passionate, male vocal",
    lyricsTheme: "深夜城市里的独白",
    language: "zh",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    streamUrl: null,
    coverUrl: null,
    durationMs: 318000,
    status: "ready",
    murekaTaskId: null,
    tags: ["r&b", "slow", "night"],
  },
  {
    title: "City Glow",
    artist: "AI Radio",
    mode: "style_variation",
    prompt: "city pop, 80s, nostalgic, female vocal",
    lyricsTheme: "复古都市霓虹",
    language: "zh",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    streamUrl: null,
    coverUrl: null,
    durationMs: 290000,
    status: "ready",
    murekaTaskId: null,
    tags: ["city pop", "nostalgic", "synth"],
  },
  {
    title: "星空告白",
    artist: "AI Radio",
    mode: "original",
    prompt: "mandopop, emotional, piano, female vocal",
    lyricsTheme: "星空下的告白",
    language: "zh",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    streamUrl: null,
    coverUrl: null,
    durationMs: 350000,
    status: "ready",
    murekaTaskId: null,
    tags: ["mandopop", "emotional", "piano"],
  },
];
